Fix monit stop/restart. Update to latest service broker.

diff --git a/jobs/aerospike_server/templates/ctl.erb b/jobs/aerospike_server/templates/ctl.erb
--- a/jobs/aerospike_server/templates/ctl.erb
+++ b/jobs/aerospike_server/templates/ctl.erb
@@ -1,8 +1,6 @@
 #!/bin/bash
 set -ax
-# RUN_DIR=/var/vcap/sys/run/aerospike
-#LOG_DIR=/var/vcap/sys/log/aerospike
-#PIDFILE=${RUN_DIR}/pid
+
 STORE_DIR=/var/vcap/store/aerospike
 DATA_DIR=/var/vcap/data/aerospike
 SERVER_DIR=/var/vcap/data/aerospike/aerospike-server
@@ -13,6 +11,118 @@ SCRIPT_DIR=$(dirname $0)
 
 exec &2>$LOG_DIR/aerospike.stdout.log
 exec &1>$LOG_DIR/aerospike.stdout.log
+
+function pid_is_running() {
+  declare pid="$1"
+  ps -p "${pid}" >/dev/null 2>&1
+}
+
+# wait_pid_death
+#
+# @param pid
+# @param timeout
+#
+# Watch a :pid: for :timeout: seconds, waiting for it to die.
+# If it dies before :timeout:, exit 0. If not, exit 1.
+#
+# Note that this should be run in a subshell, so that the current
+# shell does not exit.
+#
+function wait_pid_death() {
+  declare pid="$1" timeout="$2"
+
+  local countdown
+  countdown=$(( timeout * 10 ))
+
+  while true; do
+    if ! pid_is_running "${pid}"; then
+      return 0
+    fi
+
+    if [ ${countdown} -le 0 ]; then
+      return 1
+    fi
+
+    countdown=$(( countdown - 1 ))
+    sleep 0.1
+  done
+}
+
+# kill_and_wait
+#
+# @param pidfile
+# @param timeout [default 25s]
+#
+# For a pid found in :pidfile:, send a `kill -6`, then wait for :timeout: seconds to
+# see if it dies on its own. If not, send it a `kill -9`. If the process does die,
+# exit 0 and remove the :pidfile:. If after all of this, the process does not actually
+# die, exit 1.
+#
+# Note:
+# Monit default timeout for start/stop is 30s
+# Append 'with timeout {n} seconds' to monit start/stop program configs
+#
+function kill_and_wait() {
+  declare pidfile="$1" timeout="${2:-25}" sigkill_on_timeout="${3:-1}"
+
+  if [ ! -f "${pidfile}" ]; then
+    echo "Pidfile ${pidfile} doesn't exist"
+    return 0
+  fi
+
+  local pid
+  pid=$(head -1 "${pidfile}")
+
+  if [ -z "${pid}" ]; then
+    echo "Unable to get pid from ${pidfile}"
+    return 1
+  fi
+
+  if ! pid_is_running "${pid}"; then
+    echo "Process ${pid} is not running"
+    rm -f "${pidfile}"
+    return 0
+  fi
+
+  echo "Killing ${pidfile}: ${pid} "
+  kill "${pid}"
+
+  if ! wait_pid_death "${pid}" "${timeout}"; then
+    if [ "${sigkill_on_timeout}" = "1" ]; then
+      echo "Kill timed out, using kill -9 on ${pid}"
+      kill -9 "${pid}"
+      sleep 0.5
+    fi
+  fi
+
+  if pid_is_running "${pid}"; then
+    echo "Timed Out"
+    return 1
+  else
+    echo "Stopped"
+    rm -f "${pidfile}"
+  fi
+}
+
+start_aerospike() {
+	chown -R vcap:vcap $RUN_DIR $LOG_DIR
+	set_shmall
+	set_shmmax
+	ulimit -n 100000
+
+	pushd /var/vcap/data/aerospike/aerospike-server
+		sudo ./usr/bin/asd \
+		  	--config-file /var/vcap/jobs/aerospike_server/config/aerospike.conf \
+		  	start
+	popd
+	log_debug "LICENSE ${AEROSPIKE_LICENSE} CONFIG ${CONFIG_USER}"
+	if [ "$CONFIG_USER" == true ] && [ "$AEROSPIKE_LICENSE" == "enterprise" ] ; then
+		sleep 30s
+		aql -Uadmin -Padmin -c "create role cf_admin privileges read-write.cf_admin"
+		aql -Uadmin -Padmin -c "grant role cf_admin to admin"
+		aql -Uadmin -Padmin -c "set password ${AEROSPIKE_PASSWORD} for ${AEROSPIKE_USER}"
+	fi
+}
 
 if [ ! -d ${DATA_DIR} || ! -d ${SERVER_DIR}  ]
 then
@@ -42,30 +152,15 @@ fi
 case $1 in
 
   start)
-	chown -R vcap:vcap $RUN_DIR $LOG_DIR
-	set_shmall
-	set_shmmax
-	ulimit -n 100000
-
-	pushd /var/vcap/data/aerospike/aerospike-server
-		sudo ./usr/bin/asd \
-		  	--config-file /var/vcap/jobs/aerospike_server/config/aerospike.conf \
-		  	start
-	popd
-	log_debug "LICENSE ${AEROSPIKE_LICENSE} CONFIG ${CONFIG_USER}"
-	if [ "$CONFIG_USER" == true ] && [ "$AEROSPIKE_LICENSE" == "enterprise" ] ; then
-		sleep 30s
-		aql -Uadmin -Padmin -c "create role cf_admin privileges read-write.cf_admin"
-		aql -Uadmin -Padmin -c "grant role cf_admin to admin"
-		aql -Uadmin -Padmin -c "set password ${AEROSPIKE_PASSWORD} for ${AEROSPIKE_USER}"
-	fi
+	log_debug "STARTING SERVICE..."
+	start_aerospike
+	log_debug "FINISHED STARTING SERVICE."
     ;;
 
   stop)
-	pushd  /var/vcap/data/aerospike/aerospike-server
-		sudo ./usr/bin/asd stop
-	popd
-	echo `date` Done killing server
+	log_debug "STOPPING SERVICE..."
+	kill_and_wait $PIDFILE
+	log_debug "FINISHED STOPPING SERVICE."
     ;;
 
   *)
